### ISSUE TITLE
Размер стэка

### ISSUE THREAD

**Issue by chiefkana** [tukhfatov/CodeforcesDiv2-A#1]
Почему` nums[i + n] `не выдает ошибку **`Out of bounds`**?

**Comment by tukhfatov** [comment]
@kanatBektursyn укажи ссылку на решение. Какая задача?

**Comment by chiefkana** [comment]
https://github.com/tukhfatov/algo/commit/bf130858621f2676caa6418ff2aa1944ba5698f6

**Comment by tukhfatov** [comment]
@kanatBektursyn прочитай условие задачи [тут](https://leetcode.com/problems/shuffle-the-array/).

**Comment by chiefkana** [comment]
Спасибо

**Comment by chiefkana** [comment]
@tukhfatov 
```javascript
/**
 * @param {number[]} nums
 * @param {number} n
 * @return {number[]}
 */
var shuffle = function(nums, n) {
    let ans = [];
    
    for(let i = 0; i < n; i++){
        ans.push(nums[i])
        ans.push(nums[n + i])
    }
    
    return ans;
};
```

Это js сверхмедленный, или мне надо было через `reduce` или `map` чтобы добиться хотя бы 10 мс на результат?

**Comment by tukhfatov** [comment]
@kanatBektursyn возможно это JS медленный. Не писал на JS, не могу ответить.
